# Generated by Django 3.1.6 on 2021-02-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='descripcion',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
