# Generated by Django 3.1.6 on 2021-02-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_venta_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='comprador',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
