const Types = {
    IS_LOADING: "IS_LOADING",
    IS_READY : "IS_READY",
    AUTH_ERROR: "AUTH_ERROR",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    REGISTER_FAIL: "REGISTER_FAIL",
    LOGOUT: "LOGOUT"
};

export default Types